name: Build, Push and Deploy Docker Image to AWS ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: carzone-django

permissions:
  contents: read

jobs:
  build-push-deploy:
    name: Build, Push and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using access keys
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tags
        id: vars
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.vars.outputs.image_uri }}:${{ steps.vars.outputs.image_tag }} \
            -t ${{ steps.vars.outputs.image_uri }}:latest \
            .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.vars.outputs.image_uri }}:${{ steps.vars.outputs.image_tag }}
          docker push ${{ steps.vars.outputs.image_uri }}:latest

      - name: Deploy latest image on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 236195543546.dkr.ecr.eu-west-1.amazonaws.com

            docker pull ${{ steps.vars.outputs.image_uri }}:latest

            docker rm -f carzone_app || true

            docker run -d \
              -p 8000:8000 \
              --name carzone_app \
              --link carzone_db:db \
              -e SECRET_KEY='${{ secrets.SECRET_KEY }}' \
              -e DEBUG=False \
              -e ALLOWED_HOSTS='*' \
              -e DB_NAME=carzone_db \
              -e DB_USER=carzone_user \
              -e DB_PASSWORD=StrongPassword123 \
              -e DB_HOST=db \
              -e DB_PORT=5432 \
              ${{ steps.vars.outputs.image_uri }}:latest

      - name: Print deployed image
        run: |
          echo "Deployed image:"
          echo "${{ steps.vars.outputs.image_uri }}:${{ steps.vars.outputs.image_tag }}"
          echo "${{ steps.vars.outputs.image_uri }}:latest"